services:
  ng_static_pdf:
    container_name: ng_static_pdf
    image: thekarananand/ng_static_pdf
    networks:
      - rf_assignment
    volumes:
      - ./shared:/opt/shared:ro

  rf_backend:
    container_name: rf_backend
    image: thekarananand/rf_backend
    networks:
      - rf_assignment
    volumes:
      - ./shared:/opt/shared:rw

  rf_frontend:
    container_name: rf_frontend
    image: thekarananand/rf_frontend
    networks:
      - rf_assignment
    depends_on:
      - ng_rev_proxy
      - ng_static_pdf
      - rf_backend

  ng_rev_proxy:
    container_name: ng_rev_proxy
    image: thekarananand/ng_rev_proxy
    networks:
      - rf_assignment
    ports:
      - 8000:80

networks:
  rf_assignment:
    name: rf_assignment