name: Build & Push to DockerHub

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Image 1 (ng_rev_proxy)
      env:
        IMAGE_NAME: ng_rev_proxy
      run: |
        docker build ./${IMAGE_NAME} -t ${{ secrets.DOCKER_USERNAME }}/${IMAGE_NAME}:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/${IMAGE_NAME}:latest

    - name: Build and Push Image 2 (ng_static_pdf)
      env:
        IMAGE_NAME: ng_static_pdf
      run: |
        docker build ./${IMAGE_NAME} -t ${{ secrets.DOCKER_USERNAME }}/${IMAGE_NAME}:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/${IMAGE_NAME}:latest

    - name: Build and Push Image 3 (rf_backend)
      env:
        IMAGE_NAME: rf_backend
      run: |
        docker build ./${IMAGE_NAME} -t ${{ secrets.DOCKER_USERNAME }}/${IMAGE_NAME}:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/${IMAGE_NAME}:latest

    - name: Build and Push Image 4 (rf_frontend)
      env:
        IMAGE_NAME: rf_frontend
      run: |
        docker build ./${IMAGE_NAME} -t ${{ secrets.DOCKER_USERNAME }}/${IMAGE_NAME}:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/${IMAGE_NAME}:latest
